### ISSUE TITLE
Player hitbox does not change with model, causing several issues

### ISSUE THREAD

**Issue by muzikbike** [iPixeli/gender#1]
Currently the mod just assumes that the player's hitbox is always the adult male size (default), and it doesn't adjust according to the player's expected size. This causes an assortment of issues:

- The player is unable to fit into gaps they should ultimately be able to judging by their size. (I can definitely see why this aspect hasn't been implemented, as it causes significant gameplay differences despite these changes being intended to be largely cosmetic, and would likely also pose a problem for servers. So if this is ultimately changed, there would have to be a config option somewhere to allow/disallow hitbox size changing as to prevent any unwanted effects.)
- The player's point of view is not adjusted for their size.
- The player's shadow can end up being disproportionately large, especially compared to other mobs of similar sizes.
- In third person view, the area where the player's head would normally be doesn't match up with where it necessarily is, resulting in it being off-center.

Again, as stated before, many of these probably wouldn't be able to be fixed due to the gameplay implications, but if there is a way to do so that'd be great. There's probably other things that would fall under this issue that I haven't explicitly tested as well (reach distance, where projectiles originate from, where other mobs look, ...).
![2022-02-28_11 39 43](https://user-images.githubusercontent.com/52297970/155979788-faac7f8b-70e2-4cb7-afba-6cfa0d5890e1.png)

**Comment by iPixeli** [comment]
My intentions with this mod currently, is to change player appearance. It is not the intention of this mod to provide any non-visual advantage to players choose to be rendered smaller than default. To change the hitbox, step height, or other mechanics and abilities of the player. To do so would affect much of Minecraft's physics/mechanics which could also change significantly as new versions of Minecraft are released. For now my focus is aesthetics.
